using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using System.Diagnostics;

namespace WindowsFormsApplication1
{
    public partial class Form3 : Form
    {
        public string[] config;
        public Process P;
        public Form3()
        {
            InitializeComponent();
            //this.config = config;
        }

        private void button3_Click(object sender, EventArgs e)
        {
            string name = textBox1.Text;
            System.IO.Directory.CreateDirectory(System.IO.Directory.GetCurrentDirectory() + "/" + this.config[1] + "/" + name);
            System.IO.StreamWriter st = System.IO.File.CreateText(System.IO.Directory.GetCurrentDirectory() + "/" + this.config[1] + "/" + name + "/readme.txt");
            st.Write("Made by xenor. (Place your files here)");
            st.Flush();
            st.Close();
            System.IO.StreamWriter handle = System.IO.File.CreateText(System.IO.Directory.GetCurrentDirectory() + "/" + "/xml/create_" + name + ".xml");
            handle.Write("<!-- This file was generated by the Metin2 Unpack Helper by xenor -->\n<Buildfile version=\"1.1\">\n\t<Action type=\"create\" output=\"" + System.IO.Directory.GetCurrentDirectory() + "\\pack\\" + name + "\">\n");
            string filename = (System.IO.Directory.GetCurrentDirectory()+"pack2/"+name+"/readme.txt").Replace("/","\\");
                handle.Write("\t\t<File archivedPath=\"readme.txt\" type=\"2\"><![CDATA["+filename+"]]></File>\n");
            handle.Write("\t</Action>\n</Buildfile>");
            handle.Flush();
            handle.Close();
            try
            {
                this.P.Kill();
            }
            catch { }
            this.P = new Process();
            this.P.StartInfo.FileName = System.IO.Directory.GetCurrentDirectory() + "/" + System.IO.Directory.GetCurrentDirectory() + "/" + this.config[2];
            this.P.StartInfo.Arguments = "\"" + System.IO.Directory.GetCurrentDirectory() + "/xml/create_" + name + ".xml" + "\"";
            this.P.Start();
            Process tmp = new Process();
            tmp.StartInfo.FileName = System.IO.Directory.GetCurrentDirectory() + "/" + System.IO.Directory.GetCurrentDirectory() + "/" + this.config[1] + "/" + name;
            tmp.Start();
            this.Close();
        }

        private void textBox1_TextChanged(object sender, EventArgs e)
        {

        }

        private void Form3_Load(object sender, EventArgs e)
        {

        }
    }
}
